// flow-typed signature: 2fbaf58afef56417e0b8b522d5f15308
// flow-typed version: <<STUB>>/timbre_v^14.11.25/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'timbre'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'timbre' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'timbre/Gruntfile' {
  declare module.exports: any;
}

declare module 'timbre/misc/audio-jsonp' {
  declare module.exports: any;
}

declare module 'timbre/misc/js/chai' {
  declare module.exports: any;
}

declare module 'timbre/misc/js/codemirror' {
  declare module.exports: any;
}

declare module 'timbre/misc/js/common' {
  declare module.exports: any;
}

declare module 'timbre/misc/js/emacs' {
  declare module.exports: any;
}

declare module 'timbre/misc/js/htmlembedded' {
  declare module.exports: any;
}

declare module 'timbre/misc/js/htmlmixed' {
  declare module.exports: any;
}

declare module 'timbre/misc/js/javascript' {
  declare module.exports: any;
}

declare module 'timbre/misc/js/jquery' {
  declare module.exports: any;
}

declare module 'timbre/misc/js/mocha' {
  declare module.exports: any;
}

declare module 'timbre/misc/js/prettify' {
  declare module.exports: any;
}

declare module 'timbre/misc/js/subcollider' {
  declare module.exports: any;
}

declare module 'timbre/misc/js/underscore' {
  declare module.exports: any;
}

declare module 'timbre/misc/js/xml' {
  declare module.exports: any;
}

declare module 'timbre/src/core' {
  declare module.exports: any;
}

declare module 'timbre/src/extras/audio-jsonp' {
  declare module.exports: any;
}

declare module 'timbre/src/extras/cosc' {
  declare module.exports: any;
}

declare module 'timbre/src/extras/jsmad' {
  declare module.exports: any;
}

declare module 'timbre/src/extras/keyboard' {
  declare module.exports: any;
}

declare module 'timbre/src/extras/min/audio-jsonp.min' {
  declare module.exports: any;
}

declare module 'timbre/src/extras/min/cosc.min' {
  declare module.exports: any;
}

declare module 'timbre/src/extras/min/jsmad.min' {
  declare module.exports: any;
}

declare module 'timbre/src/extras/min/keyboard.min' {
  declare module.exports: any;
}

declare module 'timbre/src/extras/min/MoogFF.min' {
  declare module.exports: any;
}

declare module 'timbre/src/extras/min/mouse.min' {
  declare module.exports: any;
}

declare module 'timbre/src/extras/min/mp3_decode.min' {
  declare module.exports: any;
}

declare module 'timbre/src/extras/min/pico-binder.min' {
  declare module.exports: any;
}

declare module 'timbre/src/extras/min/soundfont.min' {
  declare module.exports: any;
}

declare module 'timbre/src/extras/min/webaudioapi.min' {
  declare module.exports: any;
}

declare module 'timbre/src/extras/MoogFF' {
  declare module.exports: any;
}

declare module 'timbre/src/extras/mouse' {
  declare module.exports: any;
}

declare module 'timbre/src/extras/mp3_decode' {
  declare module.exports: any;
}

declare module 'timbre/src/extras/pico-binder' {
  declare module.exports: any;
}

declare module 'timbre/src/extras/soundfont' {
  declare module.exports: any;
}

declare module 'timbre/src/extras/webaudioapi' {
  declare module.exports: any;
}

declare module 'timbre/src/modules/biquad' {
  declare module.exports: any;
}

declare module 'timbre/src/modules/chorus' {
  declare module.exports: any;
}

declare module 'timbre/src/modules/compressor' {
  declare module.exports: any;
}

declare module 'timbre/src/modules/decoder' {
  declare module.exports: any;
}

declare module 'timbre/src/modules/envelope' {
  declare module.exports: any;
}

declare module 'timbre/src/modules/fft' {
  declare module.exports: any;
}

declare module 'timbre/src/modules/oscillator' {
  declare module.exports: any;
}

declare module 'timbre/src/modules/reverb' {
  declare module.exports: any;
}

declare module 'timbre/src/modules/scissor' {
  declare module.exports: any;
}

declare module 'timbre/src/modules/stereodelay' {
  declare module.exports: any;
}

declare module 'timbre/src/objects/audio' {
  declare module.exports: any;
}

declare module 'timbre/src/objects/biquad' {
  declare module.exports: any;
}

declare module 'timbre/src/objects/buffer' {
  declare module.exports: any;
}

declare module 'timbre/src/objects/chorus' {
  declare module.exports: any;
}

declare module 'timbre/src/objects/clip' {
  declare module.exports: any;
}

declare module 'timbre/src/objects/comp' {
  declare module.exports: any;
}

declare module 'timbre/src/objects/delay' {
  declare module.exports: any;
}

declare module 'timbre/src/objects/dist' {
  declare module.exports: any;
}

declare module 'timbre/src/objects/div' {
  declare module.exports: any;
}

declare module 'timbre/src/objects/env' {
  declare module.exports: any;
}

declare module 'timbre/src/objects/eq' {
  declare module.exports: any;
}

declare module 'timbre/src/objects/fft' {
  declare module.exports: any;
}

declare module 'timbre/src/objects/fnoise' {
  declare module.exports: any;
}

declare module 'timbre/src/objects/gate' {
  declare module.exports: any;
}

declare module 'timbre/src/objects/ifft' {
  declare module.exports: any;
}

declare module 'timbre/src/objects/interval' {
  declare module.exports: any;
}

declare module 'timbre/src/objects/lag' {
  declare module.exports: any;
}

declare module 'timbre/src/objects/map' {
  declare module.exports: any;
}

declare module 'timbre/src/objects/max' {
  declare module.exports: any;
}

declare module 'timbre/src/objects/mediastream' {
  declare module.exports: any;
}

declare module 'timbre/src/objects/midicps' {
  declare module.exports: any;
}

declare module 'timbre/src/objects/midiratio' {
  declare module.exports: any;
}

declare module 'timbre/src/objects/min' {
  declare module.exports: any;
}

declare module 'timbre/src/objects/mml' {
  declare module.exports: any;
}

declare module 'timbre/src/objects/mono' {
  declare module.exports: any;
}

declare module 'timbre/src/objects/mul' {
  declare module.exports: any;
}

declare module 'timbre/src/objects/ndict' {
  declare module.exports: any;
}

declare module 'timbre/src/objects/noise' {
  declare module.exports: any;
}

declare module 'timbre/src/objects/osc' {
  declare module.exports: any;
}

declare module 'timbre/src/objects/pan' {
  declare module.exports: any;
}

declare module 'timbre/src/objects/param' {
  declare module.exports: any;
}

declare module 'timbre/src/objects/phaser' {
  declare module.exports: any;
}

declare module 'timbre/src/objects/pink' {
  declare module.exports: any;
}

declare module 'timbre/src/objects/pluck' {
  declare module.exports: any;
}

declare module 'timbre/src/objects/rec' {
  declare module.exports: any;
}

declare module 'timbre/src/objects/reverb' {
  declare module.exports: any;
}

declare module 'timbre/src/objects/schedule' {
  declare module.exports: any;
}

declare module 'timbre/src/objects/scope' {
  declare module.exports: any;
}

declare module 'timbre/src/objects/script' {
  declare module.exports: any;
}

declare module 'timbre/src/objects/selector' {
  declare module.exports: any;
}

declare module 'timbre/src/objects/spectrum' {
  declare module.exports: any;
}

declare module 'timbre/src/objects/subtract' {
  declare module.exports: any;
}

declare module 'timbre/src/objects/synthdef' {
  declare module.exports: any;
}

declare module 'timbre/src/objects/tape' {
  declare module.exports: any;
}

declare module 'timbre/src/objects/task' {
  declare module.exports: any;
}

declare module 'timbre/src/objects/timeout' {
  declare module.exports: any;
}

declare module 'timbre/src/objects/waveshaper' {
  declare module.exports: any;
}

declare module 'timbre/src/objects/zmap' {
  declare module.exports: any;
}

declare module 'timbre/test/add' {
  declare module.exports: any;
}

declare module 'timbre/test/arraywrapper' {
  declare module.exports: any;
}

declare module 'timbre/test/booleanwrapper' {
  declare module.exports: any;
}

declare module 'timbre/test/clip' {
  declare module.exports: any;
}

declare module 'timbre/test/deferred' {
  declare module.exports: any;
}

declare module 'timbre/test/div' {
  declare module.exports: any;
}

declare module 'timbre/test/events' {
  declare module.exports: any;
}

declare module 'timbre/test/functionwrapper' {
  declare module.exports: any;
}

declare module 'timbre/test/interval' {
  declare module.exports: any;
}

declare module 'timbre/test/max' {
  declare module.exports: any;
}

declare module 'timbre/test/min' {
  declare module.exports: any;
}

declare module 'timbre/test/mml' {
  declare module.exports: any;
}

declare module 'timbre/test/mul' {
  declare module.exports: any;
}

declare module 'timbre/test/numberwrapper' {
  declare module.exports: any;
}

declare module 'timbre/test/objectwrapper' {
  declare module.exports: any;
}

declare module 'timbre/test/osc' {
  declare module.exports: any;
}

declare module 'timbre/test/schedule' {
  declare module.exports: any;
}

declare module 'timbre/test/subtract' {
  declare module.exports: any;
}

declare module 'timbre/test/timbre.debug' {
  declare module.exports: any;
}

declare module 'timbre/test/timeout' {
  declare module.exports: any;
}

declare module 'timbre/test/timevalue' {
  declare module.exports: any;
}

declare module 'timbre/timbre.dev' {
  declare module.exports: any;
}

declare module 'timbre/timbre.node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'timbre/Gruntfile.js' {
  declare module.exports: $Exports<'timbre/Gruntfile'>;
}
declare module 'timbre/misc/audio-jsonp.js' {
  declare module.exports: $Exports<'timbre/misc/audio-jsonp'>;
}
declare module 'timbre/misc/js/chai.js' {
  declare module.exports: $Exports<'timbre/misc/js/chai'>;
}
declare module 'timbre/misc/js/codemirror.js' {
  declare module.exports: $Exports<'timbre/misc/js/codemirror'>;
}
declare module 'timbre/misc/js/common.js' {
  declare module.exports: $Exports<'timbre/misc/js/common'>;
}
declare module 'timbre/misc/js/emacs.js' {
  declare module.exports: $Exports<'timbre/misc/js/emacs'>;
}
declare module 'timbre/misc/js/htmlembedded.js' {
  declare module.exports: $Exports<'timbre/misc/js/htmlembedded'>;
}
declare module 'timbre/misc/js/htmlmixed.js' {
  declare module.exports: $Exports<'timbre/misc/js/htmlmixed'>;
}
declare module 'timbre/misc/js/javascript.js' {
  declare module.exports: $Exports<'timbre/misc/js/javascript'>;
}
declare module 'timbre/misc/js/jquery.js' {
  declare module.exports: $Exports<'timbre/misc/js/jquery'>;
}
declare module 'timbre/misc/js/mocha.js' {
  declare module.exports: $Exports<'timbre/misc/js/mocha'>;
}
declare module 'timbre/misc/js/prettify.js' {
  declare module.exports: $Exports<'timbre/misc/js/prettify'>;
}
declare module 'timbre/misc/js/subcollider.js' {
  declare module.exports: $Exports<'timbre/misc/js/subcollider'>;
}
declare module 'timbre/misc/js/underscore.js' {
  declare module.exports: $Exports<'timbre/misc/js/underscore'>;
}
declare module 'timbre/misc/js/xml.js' {
  declare module.exports: $Exports<'timbre/misc/js/xml'>;
}
declare module 'timbre/src/core.js' {
  declare module.exports: $Exports<'timbre/src/core'>;
}
declare module 'timbre/src/extras/audio-jsonp.js' {
  declare module.exports: $Exports<'timbre/src/extras/audio-jsonp'>;
}
declare module 'timbre/src/extras/cosc.js' {
  declare module.exports: $Exports<'timbre/src/extras/cosc'>;
}
declare module 'timbre/src/extras/jsmad.js' {
  declare module.exports: $Exports<'timbre/src/extras/jsmad'>;
}
declare module 'timbre/src/extras/keyboard.js' {
  declare module.exports: $Exports<'timbre/src/extras/keyboard'>;
}
declare module 'timbre/src/extras/min/audio-jsonp.min.js' {
  declare module.exports: $Exports<'timbre/src/extras/min/audio-jsonp.min'>;
}
declare module 'timbre/src/extras/min/cosc.min.js' {
  declare module.exports: $Exports<'timbre/src/extras/min/cosc.min'>;
}
declare module 'timbre/src/extras/min/jsmad.min.js' {
  declare module.exports: $Exports<'timbre/src/extras/min/jsmad.min'>;
}
declare module 'timbre/src/extras/min/keyboard.min.js' {
  declare module.exports: $Exports<'timbre/src/extras/min/keyboard.min'>;
}
declare module 'timbre/src/extras/min/MoogFF.min.js' {
  declare module.exports: $Exports<'timbre/src/extras/min/MoogFF.min'>;
}
declare module 'timbre/src/extras/min/mouse.min.js' {
  declare module.exports: $Exports<'timbre/src/extras/min/mouse.min'>;
}
declare module 'timbre/src/extras/min/mp3_decode.min.js' {
  declare module.exports: $Exports<'timbre/src/extras/min/mp3_decode.min'>;
}
declare module 'timbre/src/extras/min/pico-binder.min.js' {
  declare module.exports: $Exports<'timbre/src/extras/min/pico-binder.min'>;
}
declare module 'timbre/src/extras/min/soundfont.min.js' {
  declare module.exports: $Exports<'timbre/src/extras/min/soundfont.min'>;
}
declare module 'timbre/src/extras/min/webaudioapi.min.js' {
  declare module.exports: $Exports<'timbre/src/extras/min/webaudioapi.min'>;
}
declare module 'timbre/src/extras/MoogFF.js' {
  declare module.exports: $Exports<'timbre/src/extras/MoogFF'>;
}
declare module 'timbre/src/extras/mouse.js' {
  declare module.exports: $Exports<'timbre/src/extras/mouse'>;
}
declare module 'timbre/src/extras/mp3_decode.js' {
  declare module.exports: $Exports<'timbre/src/extras/mp3_decode'>;
}
declare module 'timbre/src/extras/pico-binder.js' {
  declare module.exports: $Exports<'timbre/src/extras/pico-binder'>;
}
declare module 'timbre/src/extras/soundfont.js' {
  declare module.exports: $Exports<'timbre/src/extras/soundfont'>;
}
declare module 'timbre/src/extras/webaudioapi.js' {
  declare module.exports: $Exports<'timbre/src/extras/webaudioapi'>;
}
declare module 'timbre/src/modules/biquad.js' {
  declare module.exports: $Exports<'timbre/src/modules/biquad'>;
}
declare module 'timbre/src/modules/chorus.js' {
  declare module.exports: $Exports<'timbre/src/modules/chorus'>;
}
declare module 'timbre/src/modules/compressor.js' {
  declare module.exports: $Exports<'timbre/src/modules/compressor'>;
}
declare module 'timbre/src/modules/decoder.js' {
  declare module.exports: $Exports<'timbre/src/modules/decoder'>;
}
declare module 'timbre/src/modules/envelope.js' {
  declare module.exports: $Exports<'timbre/src/modules/envelope'>;
}
declare module 'timbre/src/modules/fft.js' {
  declare module.exports: $Exports<'timbre/src/modules/fft'>;
}
declare module 'timbre/src/modules/oscillator.js' {
  declare module.exports: $Exports<'timbre/src/modules/oscillator'>;
}
declare module 'timbre/src/modules/reverb.js' {
  declare module.exports: $Exports<'timbre/src/modules/reverb'>;
}
declare module 'timbre/src/modules/scissor.js' {
  declare module.exports: $Exports<'timbre/src/modules/scissor'>;
}
declare module 'timbre/src/modules/stereodelay.js' {
  declare module.exports: $Exports<'timbre/src/modules/stereodelay'>;
}
declare module 'timbre/src/objects/audio.js' {
  declare module.exports: $Exports<'timbre/src/objects/audio'>;
}
declare module 'timbre/src/objects/biquad.js' {
  declare module.exports: $Exports<'timbre/src/objects/biquad'>;
}
declare module 'timbre/src/objects/buffer.js' {
  declare module.exports: $Exports<'timbre/src/objects/buffer'>;
}
declare module 'timbre/src/objects/chorus.js' {
  declare module.exports: $Exports<'timbre/src/objects/chorus'>;
}
declare module 'timbre/src/objects/clip.js' {
  declare module.exports: $Exports<'timbre/src/objects/clip'>;
}
declare module 'timbre/src/objects/comp.js' {
  declare module.exports: $Exports<'timbre/src/objects/comp'>;
}
declare module 'timbre/src/objects/delay.js' {
  declare module.exports: $Exports<'timbre/src/objects/delay'>;
}
declare module 'timbre/src/objects/dist.js' {
  declare module.exports: $Exports<'timbre/src/objects/dist'>;
}
declare module 'timbre/src/objects/div.js' {
  declare module.exports: $Exports<'timbre/src/objects/div'>;
}
declare module 'timbre/src/objects/env.js' {
  declare module.exports: $Exports<'timbre/src/objects/env'>;
}
declare module 'timbre/src/objects/eq.js' {
  declare module.exports: $Exports<'timbre/src/objects/eq'>;
}
declare module 'timbre/src/objects/fft.js' {
  declare module.exports: $Exports<'timbre/src/objects/fft'>;
}
declare module 'timbre/src/objects/fnoise.js' {
  declare module.exports: $Exports<'timbre/src/objects/fnoise'>;
}
declare module 'timbre/src/objects/gate.js' {
  declare module.exports: $Exports<'timbre/src/objects/gate'>;
}
declare module 'timbre/src/objects/ifft.js' {
  declare module.exports: $Exports<'timbre/src/objects/ifft'>;
}
declare module 'timbre/src/objects/interval.js' {
  declare module.exports: $Exports<'timbre/src/objects/interval'>;
}
declare module 'timbre/src/objects/lag.js' {
  declare module.exports: $Exports<'timbre/src/objects/lag'>;
}
declare module 'timbre/src/objects/map.js' {
  declare module.exports: $Exports<'timbre/src/objects/map'>;
}
declare module 'timbre/src/objects/max.js' {
  declare module.exports: $Exports<'timbre/src/objects/max'>;
}
declare module 'timbre/src/objects/mediastream.js' {
  declare module.exports: $Exports<'timbre/src/objects/mediastream'>;
}
declare module 'timbre/src/objects/midicps.js' {
  declare module.exports: $Exports<'timbre/src/objects/midicps'>;
}
declare module 'timbre/src/objects/midiratio.js' {
  declare module.exports: $Exports<'timbre/src/objects/midiratio'>;
}
declare module 'timbre/src/objects/min.js' {
  declare module.exports: $Exports<'timbre/src/objects/min'>;
}
declare module 'timbre/src/objects/mml.js' {
  declare module.exports: $Exports<'timbre/src/objects/mml'>;
}
declare module 'timbre/src/objects/mono.js' {
  declare module.exports: $Exports<'timbre/src/objects/mono'>;
}
declare module 'timbre/src/objects/mul.js' {
  declare module.exports: $Exports<'timbre/src/objects/mul'>;
}
declare module 'timbre/src/objects/ndict.js' {
  declare module.exports: $Exports<'timbre/src/objects/ndict'>;
}
declare module 'timbre/src/objects/noise.js' {
  declare module.exports: $Exports<'timbre/src/objects/noise'>;
}
declare module 'timbre/src/objects/osc.js' {
  declare module.exports: $Exports<'timbre/src/objects/osc'>;
}
declare module 'timbre/src/objects/pan.js' {
  declare module.exports: $Exports<'timbre/src/objects/pan'>;
}
declare module 'timbre/src/objects/param.js' {
  declare module.exports: $Exports<'timbre/src/objects/param'>;
}
declare module 'timbre/src/objects/phaser.js' {
  declare module.exports: $Exports<'timbre/src/objects/phaser'>;
}
declare module 'timbre/src/objects/pink.js' {
  declare module.exports: $Exports<'timbre/src/objects/pink'>;
}
declare module 'timbre/src/objects/pluck.js' {
  declare module.exports: $Exports<'timbre/src/objects/pluck'>;
}
declare module 'timbre/src/objects/rec.js' {
  declare module.exports: $Exports<'timbre/src/objects/rec'>;
}
declare module 'timbre/src/objects/reverb.js' {
  declare module.exports: $Exports<'timbre/src/objects/reverb'>;
}
declare module 'timbre/src/objects/schedule.js' {
  declare module.exports: $Exports<'timbre/src/objects/schedule'>;
}
declare module 'timbre/src/objects/scope.js' {
  declare module.exports: $Exports<'timbre/src/objects/scope'>;
}
declare module 'timbre/src/objects/script.js' {
  declare module.exports: $Exports<'timbre/src/objects/script'>;
}
declare module 'timbre/src/objects/selector.js' {
  declare module.exports: $Exports<'timbre/src/objects/selector'>;
}
declare module 'timbre/src/objects/spectrum.js' {
  declare module.exports: $Exports<'timbre/src/objects/spectrum'>;
}
declare module 'timbre/src/objects/subtract.js' {
  declare module.exports: $Exports<'timbre/src/objects/subtract'>;
}
declare module 'timbre/src/objects/synthdef.js' {
  declare module.exports: $Exports<'timbre/src/objects/synthdef'>;
}
declare module 'timbre/src/objects/tape.js' {
  declare module.exports: $Exports<'timbre/src/objects/tape'>;
}
declare module 'timbre/src/objects/task.js' {
  declare module.exports: $Exports<'timbre/src/objects/task'>;
}
declare module 'timbre/src/objects/timeout.js' {
  declare module.exports: $Exports<'timbre/src/objects/timeout'>;
}
declare module 'timbre/src/objects/waveshaper.js' {
  declare module.exports: $Exports<'timbre/src/objects/waveshaper'>;
}
declare module 'timbre/src/objects/zmap.js' {
  declare module.exports: $Exports<'timbre/src/objects/zmap'>;
}
declare module 'timbre/test/add.js' {
  declare module.exports: $Exports<'timbre/test/add'>;
}
declare module 'timbre/test/arraywrapper.js' {
  declare module.exports: $Exports<'timbre/test/arraywrapper'>;
}
declare module 'timbre/test/booleanwrapper.js' {
  declare module.exports: $Exports<'timbre/test/booleanwrapper'>;
}
declare module 'timbre/test/clip.js' {
  declare module.exports: $Exports<'timbre/test/clip'>;
}
declare module 'timbre/test/deferred.js' {
  declare module.exports: $Exports<'timbre/test/deferred'>;
}
declare module 'timbre/test/div.js' {
  declare module.exports: $Exports<'timbre/test/div'>;
}
declare module 'timbre/test/events.js' {
  declare module.exports: $Exports<'timbre/test/events'>;
}
declare module 'timbre/test/functionwrapper.js' {
  declare module.exports: $Exports<'timbre/test/functionwrapper'>;
}
declare module 'timbre/test/interval.js' {
  declare module.exports: $Exports<'timbre/test/interval'>;
}
declare module 'timbre/test/max.js' {
  declare module.exports: $Exports<'timbre/test/max'>;
}
declare module 'timbre/test/min.js' {
  declare module.exports: $Exports<'timbre/test/min'>;
}
declare module 'timbre/test/mml.js' {
  declare module.exports: $Exports<'timbre/test/mml'>;
}
declare module 'timbre/test/mul.js' {
  declare module.exports: $Exports<'timbre/test/mul'>;
}
declare module 'timbre/test/numberwrapper.js' {
  declare module.exports: $Exports<'timbre/test/numberwrapper'>;
}
declare module 'timbre/test/objectwrapper.js' {
  declare module.exports: $Exports<'timbre/test/objectwrapper'>;
}
declare module 'timbre/test/osc.js' {
  declare module.exports: $Exports<'timbre/test/osc'>;
}
declare module 'timbre/test/schedule.js' {
  declare module.exports: $Exports<'timbre/test/schedule'>;
}
declare module 'timbre/test/subtract.js' {
  declare module.exports: $Exports<'timbre/test/subtract'>;
}
declare module 'timbre/test/timbre.debug.js' {
  declare module.exports: $Exports<'timbre/test/timbre.debug'>;
}
declare module 'timbre/test/timeout.js' {
  declare module.exports: $Exports<'timbre/test/timeout'>;
}
declare module 'timbre/test/timevalue.js' {
  declare module.exports: $Exports<'timbre/test/timevalue'>;
}
declare module 'timbre/timbre.dev.js' {
  declare module.exports: $Exports<'timbre/timbre.dev'>;
}
declare module 'timbre/timbre.node.js' {
  declare module.exports: $Exports<'timbre/timbre.node'>;
}
